## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: xenial
os:
  - linux
julia:
  - 1.0
  - 1.1
  - nightly
matrix:
 allow_failures:
 - julia: nightly
notifications:
  email: false
sudo: required
before_install:
  - sudo ln -sf /usr/bin/gcc-7 /usr/bin/gcc
  - sudo ln -sf /usr/bin/g++-7 /usr/bin/g++
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-7
    - g++-7

script:
  - julia --code-coverage --inline=no -e 'using Pkg; Pkg.build(); include("test/runtests.jl");'
after_success:
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
